services:
  # Laravel API
  backend:
    image: bitnami/laravel:latest
    container_name: laravel-cust
    user: root
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=mysql-cust
      - DB_PORT=3306
      - DB_USERNAME=dev
      - DB_PASSWORD=pas
      - DB_DATABASE=custshort_db
    command: php artisan serve --host=0.0.0.0 --port=8000

  # Angular Frontend
  frontend:
    image: node:20
    working_dir: /app
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: "sh -c 'npm install && npm start -- --host 0.0.0.0 --poll 2000'"
    container_name: angular-cust

  # База данных
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=custshort_db
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=pas
    container_name: mysql-cust
    ports:
      - "3307:3306"
